### ISSUE TITLE
Quest #13010

### ISSUE THREAD

**Issue by Exitare** [Exitare/Testrealm-Core#5]
Hier noch einige Infos:

User-Name: Zee
Bereich: Quest
Itemname: Krolmir hammer der stürme
ItemID: '13010'
Fehlerbeschreibung: Npc zum abgeben nicht vorhanden.

Der NPC Thorim steht zwar, hat jedoch die Entry-ID 29445. Der richtige Thorim hätte die ID 30390.
Laut wowhead, sollte die Quest bei 29445 starten und anschließend bei 30390 abzugeben zu sein.

Temporärer Lösungsvorschlag: NPC mit der ID 30390 stellen.

Vermute, dass es irgendwas mit dem Phasing auf sich hat, normalerweise änderte sich bei den Söhnen Hodirs das phasing wenn man den Rufstatus freundlich erreicht hat.

**Comment by wasdmovement** [comment]
Quest funktioniert einwandfrei. Man darf nicht den Questcompleter verwenden, sonst überspringt man den NPC Thorim, der auf dem Schlachtfeld auftaucht und kann anschließend nicht abgeben.
